[package]
name = "server"
version = "1.1.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
reqwest = { version = "0.12.14", features = ["json"] }
dotenv = "0.15.0"
actix-cors = "0.7.1"
lazy_static = "1.5.0"
