[package]
name = "server"
version = "1.2.0"
edition = "2021"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0.223", features = ["derive"] }
serde_json = "1.0.143"
reqwest = { version = "0.12.23", features = ["json"] }
dotenv = "0.15.0"
actix-cors = "0.7.1"
lazy_static = "1.5.0"
