name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.rs"
      - "**/*.toml"
      - "**/*.lock"
  pull_request:
    branches: [main]
    paths:
      - "**/*.rs"
      - "**/*.toml"
      - "**/*.lock"

jobs:
  setup-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Rust package
        run: cargo build --release
